[package]
name = "botzr-aegis-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CLI for Aegis. Installed binary name: aegis."
readme = "README.md"

[lints]
workspace = true

[dependencies]
botzr-aegis-runtime = { workspace = true }

[[bin]]
name = "aegis"
path = "src/main.rs"
