-- AILAB-624 — move the audit_schema_version pin from 1 to 2 (D25).
--
-- The runtime emits schema 2 (AILAB-619) and ingest now accepts only 2, so a
-- row holding 1 is a row no re-ingest can ever reproduce. 001 already declares
-- the new CHECK, but CREATE TABLE IF NOT EXISTS is a no-op against a database
-- that already exists — this file is what actually moves one.
--
-- Everything runs inside a single DO block, deliberately. The guard below and
-- the constraint swap must be one atomic statement: run as three top-level
-- statements under psql (autocommit, and no ON_ERROR_STOP by default), a raise
-- in the guard would abort only itself, DROP CONSTRAINT would then succeed,
-- ADD CONSTRAINT would fail against the very rows the guard objected to, and
-- psql would exit 0 having left the table with *no* version constraint at all.
-- A DO block cannot half-apply: if it raises, nothing inside it took effect.
-- Do not split this into bare statements, and do not add BEGIN/COMMIT here —
-- apply_migrations() already runs every file in one psycopg transaction, and a
-- COMMIT inside a file would end it early.
--
-- Idempotent: re-running drops and re-adds the same named constraint.
DO $$
DECLARE
    stale bigint;
BEGIN
    IF to_regclass('public.learning_patterns') IS NULL THEN
        -- Fresh database: 001 creates the table with the v2 CHECK already, so
        -- there is nothing to move. Reachable only when this file runs without
        -- 001 (a partial AEGIS_GOVERNANCE_MIGRATIONS_DIR, or a hand-run file).
        RETURN;
    END IF;

    -- Refuse rather than delete. Stale rows are the operator's data and the
    -- operator's call; a migration that silently drops evidence to make its
    -- own constraint pass is exactly the behaviour this project exists to
    -- argue against. Decide, then re-run:
    --
    --   SELECT call_id, audit_schema_version FROM learning_patterns
    --    WHERE audit_schema_version <> 2;
    --   DELETE FROM learning_patterns WHERE audit_schema_version <> 2;
    SELECT count(*) INTO stale
      FROM public.learning_patterns
     WHERE audit_schema_version <> 2;

    IF stale > 0 THEN
        RAISE EXCEPTION
            'AILAB-624: % learning_patterns row(s) hold audit_schema_version <> 2. '
            'Audit schema 1 is no longer ingestable (spec/SPEC.md section 12), so '
            'these rows cannot be regenerated by re-ingest. Review and remove '
            'them, then re-run this migration.', stale;
    END IF;

    ALTER TABLE public.learning_patterns
        DROP CONSTRAINT IF EXISTS learning_patterns_audit_schema_version_check;

    ALTER TABLE public.learning_patterns
        ADD CONSTRAINT learning_patterns_audit_schema_version_check
        CHECK (audit_schema_version = 2);
END $$;
